# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44be6c8576ef10bfc10725e992720d72f3ff9b120c62c085da063029050bd57be8508bc315d988593d5f8bdd629d063fb9eb2791fa0b9ec4f10e3bef05d2ef4c

test:
  secret_key_base: a1896d6c0c65f555a97ec3252dc92426bf0a86b1b2a10796173d6469a3287e141e44705264ca93c3ffbf1de72a5d180258099796775ef8c0eb98cead7031d4a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
